# Generated by Django 3.0.4 on 2020-04-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='links',
        ),
        migrations.RemoveField(
            model_name='link',
            name='user',
        ),
    ]
