# Generated by Django 3.0.4 on 2020-04-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200408_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
