# Generated by Django 3.0.5 on 2020-04-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='skills_images'),
        ),
    ]
